spring.application.name=duke-free-food-finder-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/free_food_finder
spring.datasource.username=duke_admin
spring.datasource.password=3Kg65t3s
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
